# Generated by Django 6.0.5 on 2026-09-10 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Carrinho')),
                ('tipo', models.CharField(choices=[('tablet', 'Carrinho de Tablets'), ('notebook', 'Carrinho de Notebooks')], max_length=10)),
                ('disponivel', models.BooleanField(default=True)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('numero_inicial', models.PositiveIntegerField(blank=True, help_text='Primeiro número de notebook que pertence a este carrinho', null=True, verbose_name='Nº inicial do notebook')),
                ('numero_final', models.PositiveIntegerField(blank=True, help_text='Último número de notebook que pertence a este carrinho', null=True, verbose_name='Nº final do notebook')),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome da Escola')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CodigoVerificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('tipo', models.CharField(choices=[('cadastro', 'Confirmação de Cadastro'), ('redefinicao', 'Redefinição de Senha')], max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_verificacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Código de Verificação',
                'verbose_name_plural': 'Códigos de Verificação',
            },
        ),
        migrations.CreateModel(
            name='BloqueioEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do bloqueio')),
                ('horario_inicio', models.TimeField(verbose_name='Bloqueado a partir de')),
                ('horario_fim', models.TimeField(verbose_name='Bloqueado até')),
                ('motivo', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueios_criados', to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='reservas.equipamento')),
            ],
            options={
                'ordering': ['data', 'horario_inicio'],
            },
        ),
        migrations.AddField(
            model_name='equipamento',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='reservas.escola'),
        ),
        migrations.CreateModel(
            name='GrupoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_equipamento', to='reservas.escola')),
            ],
            options={
                'verbose_name': 'Grupo de Equipamento',
                'verbose_name_plural': 'Grupos de Equipamento',
                'ordering': ['nome'],
                'unique_together': {('escola', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='EquipamentoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(blank=True, help_text='Identificador interno adicional (opcional)', max_length=50, null=True, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Ex: Notebook Dell, Tablet Samsung, Projetor Epson', max_length=100)),
                ('numero_patrimonio', models.CharField(help_text='Número de identificação/patrimônio do equipamento', max_length=50, verbose_name='Número de patrimônio')),
                ('numero_serie', models.CharField(max_length=100, verbose_name='N/S')),
                ('localizacao_atual', models.CharField(max_length=150, verbose_name='Localização atual')),
                ('comentario', models.TextField(blank=True, help_text='Observações opcionais', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='reservas.grupoequipamento')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['grupo__nome', 'tipo'],
                'unique_together': {('grupo', 'numero_patrimonio'), ('grupo', 'numero_serie')},
            },
        ),
        migrations.CreateModel(
            name='PerfilAdm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requer_aprovacao', models.BooleanField(default=False, verbose_name='Reservas requerem aprovação de ADM')),
                ('pin_envio', models.CharField(blank=True, help_text='Senha de 4 dígitos para enviar fichas no tablet', max_length=4, null=True, verbose_name='PIN de envio (4 dígitos)')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='reservas.escola')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_adm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil ADM',
                'verbose_name_plural': 'Perfis ADM',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='reservas.escola')),
            ],
            options={
                'unique_together': {('escola', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_uso', models.DateField(verbose_name='Data da Reserva')),
                ('horario_inicio', models.TimeField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('horario_fim', models.TimeField()),
                ('status', models.CharField(choices=[('confirmada', 'Confirmada'), ('pendente', 'Pendente de Aprovação'), ('recusada', 'Recusada')], default='confirmada', max_length=20)),
                ('numero_notebook_unico', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº do notebook (reserva individual)')),
                ('quantidade', models.PositiveIntegerField(blank=True, help_text='Preenchido apenas nas reservas por quantidade específica.', null=True, verbose_name='Quantidade reservada')),
                ('numeracao_preenchida', models.BooleanField(default=False, verbose_name='Numeração dos notebooks preenchida')),
                ('grupo_fixo', models.UUIDField(blank=True, db_index=True, null=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.equipamento')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.escola')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.sala', verbose_name='Sala')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_origem', models.CharField(max_length=150)),
                ('local_destino', models.CharField(max_length=150)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='reservas.equipamentoinventario')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferência',
                'verbose_name_plural': 'Transferências',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='EquipamentoLiberado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores_liberados', to='reservas.equipamento')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos_liberados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('equipamento', 'professor')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='equipamento',
            unique_together={('escola', 'nome')},
        ),
        migrations.CreateModel(
            name='HorarioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Ordem de exibição dentro do período, ex: 1 para o 1º horário, 2 para o 2º horário...', verbose_name='Número do horário')),
                ('periodo', models.CharField(choices=[('manha_tarde', '1º Período Manhã/Tarde'), ('tarde_noite', '2º Período Tarde/Noite')], default='manha_tarde', max_length=20, verbose_name='Período')),
                ('horario_inicio', models.TimeField(verbose_name='Início')),
                ('horario_fim', models.TimeField(verbose_name='Fim')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para esconder este horário sem precisar excluir', verbose_name='Disponível para reserva')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_aula', to='reservas.escola')),
            ],
            options={
                'verbose_name': 'Horário de Aula',
                'verbose_name_plural': 'Horários de Aula',
                'ordering': ['periodo', 'numero'],
                'unique_together': {('escola', 'periodo', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('ativo', models.BooleanField(default=True, verbose_name='Está funcionando')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to='reservas.equipamento')),
            ],
            options={
                'unique_together': {('equipamento', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='PerfilProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(blank=True, help_text='Formato: DDD + número, ex: 11999998888', max_length=20, null=True, verbose_name='Número de WhatsApp')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='reservas.escola')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_professor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Professor',
                'verbose_name_plural': 'Perfis dos Professores',
                'unique_together': {('escola', 'whatsapp')},
            },
        ),
        migrations.CreateModel(
            name='RegistroUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_notebook', models.IntegerField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.aluno')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva')),
            ],
            options={
                'unique_together': {('reserva', 'aluno')},
            },
        ),
        migrations.CreateModel(
            name='NumeroReservaQuantidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros_quantidade', to='reservas.reserva')),
            ],
            options={
                'unique_together': {('reserva', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='NotificacaoFichaAusente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva')),
            ],
            options={
                'unique_together': {('reserva',)},
            },
        ),
    ]
