# Generated by Django 6.0.5 on 2026-06-16 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Carrinho')),
                ('tipo', models.CharField(choices=[('tablet', 'Carrinho de Tablets'), ('notebook', 'Carrinho de Notebooks')], max_length=10)),
                ('disponivel', models.BooleanField(default=True)),
                ('quantidade', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilAdm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requer_aprovacao', models.BooleanField(default=False, verbose_name='Reservas requerem aprovação de ADM')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_adm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil ADM',
                'verbose_name_plural': 'Perfis ADM',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_uso', models.DateField(verbose_name='Data da Reserva')),
                ('horario_inicio', models.TimeField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('horario_fim', models.TimeField()),
                ('status', models.CharField(choices=[('confirmada', 'Confirmada'), ('pendente', 'Pendente de Aprovação'), ('recusada', 'Recusada')], default='confirmada', max_length=20)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.equipamento')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.sala', verbose_name='Sala')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.sala')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_notebook', models.IntegerField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.aluno')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva')),
            ],
            options={
                'unique_together': {('reserva', 'aluno')},
            },
        ),
        migrations.CreateModel(
            name='NotificacaoFichaAusente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva')),
            ],
            options={
                'unique_together': {('reserva',)},
            },
        ),
    ]
