# Generated by Django 6.0.5 on 2026-09-10 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilProfessorEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escola_ativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professores_ativos_multiplos', to='reservas.escola', verbose_name='Escola atualmente selecionada')),
                ('escolas', models.ManyToManyField(related_name='professores_multiplos', to='reservas.escola', verbose_name='Escolas onde trabalha')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_escola', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Escola do Professor',
                'verbose_name_plural': 'Perfis Escola dos Professores',
            },
        ),
    ]
