# Generated by Django 6.0.5 on 2026-06-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='numero_final',
            field=models.PositiveIntegerField(blank=True, help_text='Último número de notebook que pertence a este carrinho', null=True, verbose_name='Nº final do notebook'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='numero_inicial',
            field=models.PositiveIntegerField(blank=True, help_text='Primeiro número de notebook que pertence a este carrinho', null=True, verbose_name='Nº inicial do notebook'),
        ),
    ]
