# Generated by Django 6.0.5 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_perfilprofessorescola'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='campos_inventario',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='equipamentoinventario',
            name='dados_personalizados',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
