# Generated by Django 6.0.5 on 2026-06-24 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_equipamento_numero_final_equipamento_numero_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('ativo', models.BooleanField(default=True, verbose_name='Está funcionando')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to='reservas.equipamento')),
            ],
            options={
                'unique_together': {('equipamento', 'numero')},
            },
        ),
    ]
