# Generated by Django 6.0.5 on 2026-07-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_notebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='quantidade',
            field=models.PositiveIntegerField(blank=True, help_text='Preenchido apenas nas reservas por quantidade específica. Nulo = reserva do carrinho inteiro.', null=True, verbose_name='Quantidade reservada'),
        ),
    ]
