# Generated by Django 6.0.5 on 2026-09-22 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_campos_personalizados_inventario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAdmEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requer_aprovacao', models.BooleanField(default=False, verbose_name='Reservas requerem aprovação de ADM')),
                ('pin_envio', models.CharField(blank=True, help_text='Senha de 4 dígitos para enviar fichas no tablet', max_length=4, null=True, verbose_name='PIN de envio (4 dígitos)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escola_ativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administradores_ativos_multiplos', to='reservas.escola', verbose_name='Escola atualmente selecionada')),
                ('escolas', models.ManyToManyField(related_name='administradores_multiplos', to='reservas.escola', verbose_name='Escolas onde é admin')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_adm_escola', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Admin (múltiplas escolas)',
                'verbose_name_plural': 'Perfis Admin (múltiplas escolas)',
            },
        ),
    ]
