# Generated by Django 6.0.5 on 2026-09-22 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_perfiladmescola'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilAdmEscola',
        ),
    ]
