# Generated by Django 6.0.5 on 2026-07-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_reserva_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='numero_notebook_unico',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº do notebook (reserva individual)'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='quantidade',
            field=models.PositiveIntegerField(blank=True, help_text='Preenchido apenas nas reservas por quantidade específica.', null=True, verbose_name='Quantidade reservada'),
        ),
    ]
