# Generated by Django 6.0.5 on 2026-07-15 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_reserva_numero_notebook_unico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='numeracao_preenchida',
            field=models.BooleanField(default=False, verbose_name='Numeração dos notebooks preenchida'),
        ),
        migrations.CreateModel(
            name='NumeroReservaQuantidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros_quantidade', to='reservas.reserva')),
            ],
            options={
                'unique_together': {('reserva', 'numero')},
            },
        ),
    ]
