# Generated by Django 6.0.5 on 2026-07-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_reserva_numeracao_preenchida_numeroreservaquantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiladm',
            name='pin_envio',
            field=models.CharField(blank=True, help_text='Senha de 4 dígitos para enviar fichas no tablet', max_length=4, null=True, verbose_name='PIN de envio (4 dígitos)'),
        ),
    ]
