# Generated by Django 6.0.5 on 2026-07-22 13:21
<<<<<<< HEAD

from django.db import migrations, models
=======
from django.db import migrations
>>>>>>> cd70c9f3c2ad19096a8a59e9df72a1f8d6e86808


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_recria_perfiladm_notificacao'),
    ]

    operations = [
<<<<<<< HEAD
        migrations.AddField(
            model_name='perfiladm',
            name='pin_envio',
            field=models.CharField(blank=True, help_text='Senha de 4 dígitos para enviar fichas no tablet', max_length=4, null=True, verbose_name='PIN de envio (4 dígitos)'),
        ),
=======
        # Campo pin_envio já foi criado na migration 0007.
        # Esta migration existe apenas para manter a numeração/histórico
        # consistente com o que já está registrado em produção.
>>>>>>> cd70c9f3c2ad19096a8a59e9df72a1f8d6e86808
    ]
