# Generated by Django 6.0.5 on 2026-07-22 13:21

from django.db import migrations, models
from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_recria_perfiladm_notificacao'),
    ]

    operations = [
        # Campo pin_envio já foi criado na migration 0007.
        # Esta migration existe apenas para manter a numeração/histórico
        # consistente com o que já está registrado em produção.
    ]
