# Generated by Django 6.0.5 on 2026-08-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_codigoverificacao_perfilprofessor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilprofessor',
            name='whatsapp_verificado',
        ),
        migrations.AlterField(
            model_name='perfilprofessor',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Formato: DDD + número, ex: 11999998888', max_length=20, null=True, unique=True, verbose_name='Número de WhatsApp'),
        ),
    ]
