# Generated by Django 6.1.1 on 2026-09-25 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_vincular_escola_padrao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escola',
            options={'ordering': ['nome'], 'verbose_name': 'Escola', 'verbose_name_plural': 'Escolas'},
        ),
        migrations.AlterField(
            model_name='escola',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='nome',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nome da Escola'),
        ),
        migrations.AlterField(
            model_name='perfilprofessor',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='reservas.escola'),
        ),
        migrations.CreateModel(
            name='PerfilProfessorEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cargo', models.CharField(default='Professor', max_length=100, verbose_name='Função')),
                ('escola_ativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professores_ativos_multiplos', to='reservas.escola', verbose_name='Escola atualmente selecionada')),
                ('escolas', models.ManyToManyField(related_name='professores_multiplos', to='reservas.escola', verbose_name='Escolas onde trabalha')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_escola', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Escola do Professor',
                'verbose_name_plural': 'Perfis Escola dos Professores',
            },
        ),
    ]
