# Generated by Django 6.0.5 on 2026-08-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_remove_perfilprofessor_whatsapp_verificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='grupo_fixo',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
