# Generated by Django 6.0.5 on 2026-08-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_reserva_grupo_fixo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Ordem de exibição, ex: 1 para o 1º horário, 2 para o 2º horário...', verbose_name='Número do horário')),
                ('horario_inicio', models.TimeField(verbose_name='Início')),
                ('horario_fim', models.TimeField(verbose_name='Fim')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para esconder este horário sem precisar excluir', verbose_name='Disponível para reserva')),
            ],
            options={
                'verbose_name': 'Horário de Aula',
                'verbose_name_plural': 'Horários de Aula',
                'ordering': ['numero'],
            },
        ),
    ]
