# Generated by Django 6.0.5 on 2026-08-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_horarioaula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horarioaula',
            options={'ordering': ['periodo', 'numero'], 'verbose_name': 'Horário de Aula', 'verbose_name_plural': 'Horários de Aula'},
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='periodo',
            field=models.CharField(choices=[('manha_tarde', '1º Período Manhã/Tarde'), ('tarde_noite', '2º Período Tarde/Noite')], default='manha_tarde', max_length=20, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='horarioaula',
            name='numero',
            field=models.PositiveIntegerField(help_text='Ordem de exibição dentro do período, ex: 1 para o 1º horário, 2 para o 2º horário...', verbose_name='Número do horário'),
        ),
    ]
