# Generated by Django 6.0.5 on 2026-09-01 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0013_alter_horarioaula_options_horarioaula_periodo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueioEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do bloqueio')),
                ('horario_inicio', models.TimeField(verbose_name='Bloqueado a partir de')),
                ('horario_fim', models.TimeField(verbose_name='Bloqueado até')),
                ('motivo', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueios_criados', to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='reservas.equipamento')),
            ],
            options={
                'ordering': ['data', 'horario_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EquipamentoLiberado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores_liberados', to='reservas.equipamento')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos_liberados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('equipamento', 'professor')},
            },
        ),
    ]
