# Generated by Django 6.0.5 on 2026-09-02 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0014_bloqueioequipamento_equipamentoliberado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Grupo de Equipamento',
                'verbose_name_plural': 'Grupos de Equipamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EquipamentoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Ex: Notebook Dell, Tablet Samsung, Projetor Epson', max_length=100)),
                ('numero_patrimonio', models.CharField(help_text='Número de identificação/patrimônio do equipamento', max_length=50, unique=True, verbose_name='Número de patrimônio')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='N/S')),
                ('localizacao_atual', models.CharField(max_length=150, verbose_name='Localização atual')),
                ('comentario', models.TextField(blank=True, help_text='Observações opcionais', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='reservas.grupoequipamento')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['grupo__nome', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_origem', models.CharField(max_length=150)),
                ('local_destino', models.CharField(max_length=150)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='reservas.equipamentoinventario')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferência',
                'verbose_name_plural': 'Transferências',
                'ordering': ['-data'],
            },
        ),
    ]
