# Generated by Django 6.0.5 on 2026-09-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0015_grupoequipamento_equipamentoinventario_transferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamentoinventario',
            name='identificador',
            field=models.CharField(blank=True, help_text='Identificador interno adicional (opcional)', max_length=50, null=True, verbose_name='ID'),
        ),
    ]
