# Generated by Django 6.1.1 on 2026-09-26 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0015_transferencia_escola'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reserva',
            new_name='reservas_re_escola__3cd86f_idx',
            old_name='reserva_school_slot_idx',
        ),
        migrations.RenameIndex(
            model_name='reserva',
            new_name='reservas_re_equipam_706bdd_idx',
            old_name='reserva_equipment_slot_idx',
        ),
        migrations.RenameIndex(
            model_name='reserva',
            new_name='reservas_re_profess_e86b0f_idx',
            old_name='reserva_professor_date_idx',
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='quantidade',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='perfiladm',
            name='pin_envio',
            field=models.CharField(blank=True, help_text='Senha de 4 dígitos para enviar fichas no tablet', max_length=128, null=True, verbose_name='PIN de envio'),
        ),
    ]
